name: post

on:
  push:
  workflow_dispatch:
    inputs:
      student:
        type: boolean
        required: false
        default: false
        description: "deploy student app"
      manager:
        type: boolean
        required: false
        default: false
        description: "deploy manager app"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
      - run: echo "event_name ${{ github.event_name }}"
      - run: echo ${{ github.event.workflow_run.event }}
      - name: student
        if: >
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.student == 'true')
        run: echo "student, ${{ github.event.inputs.student }}"
      - name: manager
        if: >
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.manager == 'true')
        run: echo "manager, ${{ github.event.inputs.manager }}"
