name: trigger another workflow

on:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'post.yml',
              ref: 'main',
              inputs: {
                student: "true",
                manager: "false"
              }
            })
